name: Continuous Integration and Environment Setup

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manually trigger the workflow

jobs:
  set_env_and_lint:
    name: Set Environment and Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set environment variables
        env:
          SECRET_API_KEY: ${{ secrets.API_ROUTE }}
          SECRET_APP_KEY: ${{ secrets.APP_ROUTE }}
        run: |
          echo "SECRET_API_KEY=${SECRET_API_KEY}"
          echo "SECRET_APP_KEY=${SECRET_APP_KEY}"
          echo "SECRET_API_KEY=${SECRET_API_KEY}" >> .env
          echo "SECRET_APP_KEY=${SECRET_APP_KEY}" >> .env

      - name: Install dependencies
        run: yarn install

      - name: Build production bundle
        run: yarn build

      - name: Run Linter
        run: yarn lint
