name: Continuos integration

on: [push]
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: Run Linter
        uses: borales/actions-yarn@v4
        with:
          cmd: lint # will run `yarn lint` command
      # - name: Run Testing
      #   run: npm run test


name: Auto Set .env
push:  # Replace with the event that triggers the workflow
    branches:
      - main  # Replace with your desired branch name

jobs:
  set_env:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set environment variables
        env:
          SECRET_API_KEY: ${{ secrets.API_ROUTE }}
          SECRET_APP_KEY: ${{ secrets.API_ROUTE }}
        run: |
          echo "SECRET_KEY=${SECRET_API_KEY}" > .env
          echo "ANOTHER_SECRET=${SECRET_APP_KEY}" >> .env
